version: '2'
services:
  teamspeak:
    image: phaldan/teamspeak:3.0.13.8
    environment:
      - TS_DBPLUGIN=ts3db_mariadb
      - TS_DBSQLCREATEPATH=create_mariadb/
      - TS_DBHOST=mysql
      - TS_DBDATABASE=teamspeak
      - TS_DBPASSWORD=changeme
    volumes:
      - ./files:/teamspeak/files
      - ./logs:/teamspeak/logs
    links:
      - mysql
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
  mysql:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=teamspeak
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql
