version: '2'
services:
  teamspeak:
    image: kleberbaum/teamspeak:latest
    environment:
      - TS_DBPLUGIN=ts3db_mariadb
      - TS_DBSQLCREATEPATH=create_mariadb/
      - TS_DBHOST=mysql
      - TS_DBDATABASE=teamspeak
      - TS_DBPASSWORD=changeme
    volumes:
      - ./files:/teamspeak/files
      - ./logs:/teamspeak/logs
    links:
      - mysql
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=teamspeak
      - MYSQL_ROOT_PASSWORD=b3secure
    volumes:
      - ./mysql:/var/lib/mysql
